/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  IEarth,
  IEarthInterface,
} from "../../../contracts/Earthereum.sol/IEarth";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610274806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806318160ddd1461004657806370a0823114610064578063a9059cbb14610094575b600080fd5b61004e6100c4565b60405161005b91906100f1565b60405180910390f35b61007e6004803603810190610079919061016f565b6100c9565b60405161008b91906100f1565b60405180910390f35b6100ae60048036038101906100a991906101c8565b6100d0565b6040516100bb9190610223565b60405180910390f35b600090565b6000919050565b600092915050565b6000819050919050565b6100eb816100d8565b82525050565b600060208201905061010660008301846100e2565b92915050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061013c82610111565b9050919050565b61014c81610131565b811461015757600080fd5b50565b60008135905061016981610143565b92915050565b6000602082840312156101855761018461010c565b5b60006101938482850161015a565b91505092915050565b6101a5816100d8565b81146101b057600080fd5b50565b6000813590506101c28161019c565b92915050565b600080604083850312156101df576101de61010c565b5b60006101ed8582860161015a565b92505060206101fe858286016101b3565b9150509250929050565b60008115159050919050565b61021d81610208565b82525050565b60006020820190506102386000830184610214565b9291505056fea26469706673582212200a591a0b56d6007bd90bd343c8d628b677c3c0dd0e5b9a55718abd294ca3b88564736f6c63430008140033";

type IEarthConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: IEarthConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class IEarth__factory extends ContractFactory {
  constructor(...args: IEarthConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      IEarth & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): IEarth__factory {
    return super.connect(runner) as IEarth__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IEarthInterface {
    return new Interface(_abi) as IEarthInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IEarth {
    return new Contract(address, _abi, runner) as unknown as IEarth;
  }
}
